/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ifaces;

import Clases.*;
import Control.ArticuloC;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melón
 */
public class ArticuloV1 extends javax.swing.JFrame {
    DefaultTableModel mitabla;


    /**
     * Creates new form ArticuloV1
     */
    public ArticuloV1() {
        initComponents();
        cargarArticulos("");
       
    }
    
   
    public void cargarArticulos(String busqueda){
        String [] Titulo = {"Codigo","Descripcion","Precio","Stock","Tipo","Proveedor"};
        mitabla=new DefaultTableModel(null,Titulo);
        tblArt2.setModel(mitabla);
        try{
        ArticuloC artC = new ArticuloC();
        ArrayList<Articulo> Lista=artC.ArticulosPorProveedor(busqueda,CompraV1.txtProID.getText());
        Object []fila= new Object[6];
        
        for(int i =0; i < Lista.size(); i++){
                fila[0]=Lista.get(i).getArtID();
                fila[1]=Lista.get(i).getArtNombre();
                fila[2]=Lista.get(i).getArtPrecio();
                fila[3]=Lista.get(i).getArtStock();
                fila[4]=Lista.get(i).getMiCategoria().getCat_nombre();
                fila[5]=Lista.get(i).getMiProveedor().getPerNombre();
                       
                mitabla.addRow(fila);          
            }
        }catch(Exception e){    
            tblArt2.setModel(mitabla);

        }
    }
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Anadir = new javax.swing.JPopupMenu();
        AnadirArt = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArt2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        AnadirArt.setText("Añadir Articulo");
        AnadirArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirArtActionPerformed(evt);
            }
        });
        Anadir.add(AnadirArt);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código o Nombre");

        jButton2.setText("Buscar Articulo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblArt2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }};
            tblArt2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            tblArt2.setComponentPopupMenu(Anadir);
            tblArt2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jScrollPane1.setViewportView(tblArt2);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE))
            );

            jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            jLabel2.setText("Añadir Articulos");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(42, 42, 42)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(jLabel1))
                    .addGap(34, 34, 34)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarArticulos(txtBuscar.getText());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AnadirArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirArtActionPerformed
                   
    try {
     
         DefaultTableModel tabladet = (DefaultTableModel) CompraV1.tbl.getModel();
         String[]  dato=new String[7];
         
         int  fila = tblArt2.getSelectedRow();
       
         if(fila==-1)
         {
             JOptionPane.showMessageDialog(null, "No  ha seleccionado ningun registro");
         }
         
         else
          {
          String artId=tblArt2.getValueAt(fila, 0).toString();
          String artNombre=tblArt2.getValueAt(fila, 1).toString();
          String artProveedor=tblArt2.getValueAt(fila, 5).toString();
          String artTipo=tblArt2.getValueAt(fila, 4).toString();
          String artPrecio=tblArt2.getValueAt(fila, 2).toString();
          String CantIngresada=JOptionPane.showInputDialog("ingrese cantidad");
          int total=Integer.parseInt(CantIngresada)*Integer.parseInt(artPrecio);
          String CantExistente=tblArt2.getValueAt(fila, 3).toString();
          
          if(Integer.parseInt(CantIngresada)<=Integer.parseInt(CantExistente) && Integer.parseInt(CantIngresada)!=0 && Integer.parseInt(CantIngresada)>0 )
          {
            dato[0]=artId;
            dato[1]=artNombre;
            dato[2]=artProveedor;
            dato[3]=artTipo;
            dato[4]=CantIngresada;
            dato[5]=artPrecio;
            dato[6]=Integer.toString(total);

          
            tabladet.addRow(dato);
        
            VentaV1.tb.setModel(tabladet);
          }
          else {
              JOptionPane.showMessageDialog(null, "ingrese una cantidad válida o revise el stock");
          }
        }
         
    
    }
    catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null,"Ingrese una cantidad válida");
            }
                                              

    }//GEN-LAST:event_AnadirArtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticuloV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticuloV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticuloV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticuloV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArticuloV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Anadir;
    private javax.swing.JMenuItem AnadirArt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArt2;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
