/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ifaces;

import Clases.Cliente;
import Control.ClienteC;
import javax.swing.JOptionPane;

/**
 *
 * @author Melón
 */
public class ClienteV extends javax.swing.JFrame {

    /**
     * Creates new form ClienteV
     */
    public ClienteV() {
        initComponents();
        setLocationRelativeTo(null);        
        btnmod.setEnabled(false);
        btnreg.setEnabled(false);
    }
    
    public void RegistraCliente(){
            ClienteC cliC = new ClienteC();
     
        if(camposLlenos()){
            if(cliC.InsertCliente(txtCrut.getText(),txtCnombre.getText(),txtCdireccion.getText(),
                           txtCtelefono.getText(),txtCcorreo.getText())){
                                JOptionPane.showMessageDialog(null, "Registro guardado");
                                limpiarCampos();                                
                            }
                    else{
                        JOptionPane.showMessageDialog(null, "No se puede guardar, verifique que los datos esten completos ");
                    }
        }else{
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos");
        }
             System.out.print(this.camposLlenos());
    }
    
    
    
    public void ModificarCliente(){
           ClienteC cliC = new ClienteC();
     if(camposLlenos()){
        if(cliC.UpdateCliente(txtCrut.getText(),txtCnombre.getText(),txtCdireccion.getText(),txtCtelefono.getText(),txtCcorreo.getText())){
                                JOptionPane.showMessageDialog(null, "Registro modificado");
                                limpiarCampos();
                                
                            }
                    else{
                        JOptionPane.showMessageDialog(null, "No pude modificar ");
                    }
        }
        else{
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos");
        }
    
    }
    
    
    
    
    public void MostrarCliente(){
        ClienteC miControl=new ClienteC();
        if( miControl.siExisteCliente(txtCrut.getText())){
            txtCrut.setEnabled(false);
            btnmod.setEnabled(true);
            Cliente micli= miControl.recupera(txtCrut.getText());
            txtCrut.setText(micli.getPerID());
            txtCnombre.setText(micli.getPerNombre());
            txtCdireccion.setText(micli.getPerDireccion());
            txtCtelefono.setText(micli.getPerTelefono());
            txtCcorreo.setText(micli.getCliCorreo());   
            }
        else{
             JOptionPane.showMessageDialog(null, "Rut no existe");
             btnreg.setEnabled(true);
            }

        }
    
    
    public void limpiarCampos(){
        txtCrut.setEnabled(true);
        txtCrut.setText("");
        txtCnombre.setText("");
        txtCdireccion.setText("");
        txtCtelefono.setText("");
        txtCcorreo.setText("");   
        btnmod.setEnabled(false);
        btnreg.setEnabled(false);
    }
    
    
    public boolean camposLlenos(){
        boolean[] campo = new boolean[5];
        boolean m=true;
        campo[0]=txtCrut.getText().isEmpty();
        campo[1]=txtCnombre.getText().isEmpty();
        campo[2]=txtCdireccion.getText().isEmpty();
        campo[3]=txtCtelefono.getText().isEmpty();
        campo[4]=txtCcorreo.getText().isEmpty();
            if(campo[0] || campo[1] || campo[2] || campo[3] || campo[4] ){
                m=false;
            }else{
                m=true;
            }
                return m;
    }
    
    
    
    public void BloquearDesbloquear(boolean a, boolean b, boolean c, boolean d, boolean e){
        txtCrut.setEditable(a);
        txtCnombre.setEditable(b);
        txtCdireccion.setEditable(c);
        txtCtelefono.setEditable(d);
        txtCcorreo.setEditable(e);
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCrut = new javax.swing.JTextField();
        txtCnombre = new javax.swing.JTextField();
        txtCdireccion = new javax.swing.JTextField();
        txtCtelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnreg = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        btnvol = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCcorreo = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCrut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCrutFocusLost(evt);
            }
        });

        jLabel1.setText("Rut");

        jLabel2.setText("nombre");

        jLabel3.setText("dirección");

        jLabel4.setText("telefono");

        btnreg.setText("Registrar");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });

        btnmod.setText("Modificar");
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });

        btnvol.setText("Volver");
        btnvol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolActionPerformed(evt);
            }
        });

        jButton4.setText("limpiar Campos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cliente");

        jLabel8.setText("correo");

        jToggleButton1.setText("Buscar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addComponent(txtCrut)
                                        .addComponent(txtCdireccion)
                                        .addComponent(txtCtelefono))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnreg)
                        .addGap(34, 34, 34)
                        .addComponent(btnmod)
                        .addGap(45, 45, 45)
                        .addComponent(btnvol)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreg)
                    .addComponent(btnmod)
                    .addComponent(btnvol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCrutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrutFocusLost
        
    }//GEN-LAST:event_txtCrutFocusLost

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
        RegistraCliente();
    }//GEN-LAST:event_btnregActionPerformed

 
    
    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        ModificarCliente();
    }//GEN-LAST:event_btnmodActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnvolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnvolActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        MostrarCliente();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnreg;
    private javax.swing.JButton btnvol;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtCcorreo;
    private javax.swing.JTextField txtCdireccion;
    private javax.swing.JTextField txtCnombre;
    private javax.swing.JTextField txtCrut;
    private javax.swing.JTextField txtCtelefono;
    // End of variables declaration//GEN-END:variables
}
